version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    ports:
      - "8000:8000"
  mysql:
    image: "mysql:5.7"
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_secret
      - MYSQL_ROOT_PASSWORD=supersecret
